### ISSUE TITLE
Change filenames

### ISSUE THREAD

**Issue by DreamsOfCerulean** [LostLetter-dev/CallOfL4D2#28]
Currently, filenames are a bit confusing to work with and they need a change to be better suited to what they actually contain, even if the plan is to get rid of them soon.

**Comment by LostLetter-dev** [comment]
Yeahhh... Not something that'll change anytime soon.

In the hammer editor, especially when using Wine's windows emulation, it is absurdly tedious to appropriately edit, add, or remove files easily. Now I could fix all of this, but it would take an absurd amount of time to do so, and simply isn't worth the effort.

AKA. I'm lazy, sorry.
